name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo 1 ${{ vars.REGISTRY }} 2 ${{ secrets.REGISTRY_USERNAME }} 3 ${{ secrets.REGISTRY }}
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/nfyxhan/tr_ocr:$(date +%s)
      
    - name: Login to Ali Docker
      uses: docker/login-action@v1
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ vars.REGISTRY }}/tc-ocr:v0.0.0


